<?php

$form = array(
    'title' => 'Front-End Article Submission',
    'description' => '',
    'labelPlacement' => 'top_label',
    'descriptionPlacement' => 'below',
    'subLabelPlacement' => 'below',
    'cssClass' => '',
    'enableHoneypot' => true,
    'fields' => array(
        array(
            'type' => 'text',
            'id' => 1,
            'label' => 'Title',
            'description' => 'Please enter the title of the new release. Keep the title concise, around 60-75 characters',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'layoutGridColumnSpan' => 12,
            'layoutGroupId' => '67e8e494',
        ),
        array(
            'type' => 'textarea',
            'id' => 2,
            'label' => 'Excerpt',
            'description' => 'Provide a brief summary or teaser for the new release. This will appear in search results and previews.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'layoutGridColumnSpan' => 12,
            'layoutGroupId' => '34bd107a',
            'useRichTextEditor' => true,
        ),
        array(
            'type' => 'textarea',
            'id' => 3,
            'label' => 'Body',
            'description' => 'Compose the main content of the release here. Include relevant information, quotes, and details. Incorporate relevant keywords naturally throughout the text to improve search engine ranking.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'layoutGridColumnSpan' => 12,
            'layoutGroupId' => '74c2c685',
            'useRichTextEditor' => true,
        ),
        array(
            'type' => 'text',
            'id' => 4,
            'label' => 'Tags',
            'description' => 'Add tags separated by a comma. Note that 3 to 6 tags are recommended.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'layoutGridColumnSpan' => 12,
            'layoutGroupId' => '1c37dcf7',
        ),
        array(
            'type' => 'select',
            'id' => 5,
            'label' => 'Category',
            'description' => 'Select the appropriate category for this release.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'choices' => array(
                array('text' => 'Cover Story', 'value' => 'Cover Story'),
                array('text' => 'Press Release', 'value' => 'Press Release'),
                array('text' => 'PSI in the News', 'value' => 'PSI in the News')
            ),
            'layoutGridColumnSpan' => 6,
            'layoutGroupId' => '36ed8c2b',
        ),
        array(
            'type' => 'fileupload',
            'id' => 6,
            'label' => 'Featured Image',
            'description' => 'Upload a high quality image. This will be displayed at the top of the article. Please ensure the filename is human readable.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'maxFiles' => 1,
            'multipleFiles' => true,
            'allowedExtensions' => 'jpg, jpeg, png, gif',
            'layoutGridColumnSpan' => 6,
            'layoutGroupId' => '36ed8c2b',
            'uploadMediaLibrary' => true,
            'gpfupEnable' => true,
        ),
        array(
            'type' => 'multiselect',
            'id' => 7,
            'label' => 'Related Staff',
            'description' => 'Please select all staff members who are associated with this release.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'choices' => array(
                array('text' => 'First Choice', 'value' => 'First Choice'),
                array('text' => 'Second Choice', 'value' => 'Second Choice'),
                array('text' => 'Third Choice', 'value' => 'Third Choice')
            ),
            'layoutGridColumnSpan' => 6,
            'layoutGroupId' => '6ab3004c',
            'gppaChoicesEnabled' => true,
            'gppaChoicesObjectType' => 'user',
        ),
        array(
            'type' => 'multiselect',
            'id' => 8,
            'label' => 'Related Projects',
            'description' => 'Please select all projects which are associated with this release.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'layoutGridColumnSpan' => 6,
            'layoutGroupId' => '6ab3004c',
            'gppaChoicesEnabled' => true,
            'gppaChoicesObjectType' => 'post',
        ),
        array(
            'type' => 'html',
            'id' => 9,
            'label' => 'HTML Block',
            'content' => '<div class="project-list"></div>',
            'layoutGridColumnSpan' => 12,
            'layoutGroupId' => '03a5beea',
        ),
        array(
            'type' => 'fileupload',
            'id' => 10,
            'label' => 'Additional Image',
            'description' => 'Upload an optional image to complement the article. These are displayed at the bottom of the article page.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'maxFiles' => 1,
            'multipleFiles' => true,
            'allowedExtensions' => 'jpg, jpeg, png, gif',
            'layoutGridColumnSpan' => 4,
            'layoutGroupId' => '3b7dae73',
            'uploadMediaLibrary' => true,
            'gpfupEnable' => true,
        ),
        array(
            'type' => 'fileupload',
            'id' => 11,
            'label' => 'Additional Image',
            'description' => 'Upload an optional image to complement the article. These are displayed at the bottom of the article page.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'maxFiles' => 1,
            'multipleFiles' => true,
            'allowedExtensions' => 'jpg, jpeg, png, gif',
            'layoutGridColumnSpan' => 4,
            'layoutGroupId' => '3b7dae73',
            'uploadMediaLibrary' => true,
            'gpfupEnable' => true,
        ),
        array(
            'type' => 'fileupload',
            'id' => 12,
            'label' => 'Additional Image',
            'description' => 'Upload an optional image to complement the article. These are displayed at the bottom of the article page.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'maxFiles' => 1,
            'multipleFiles' => true,
            'allowedExtensions' => 'jpg, jpeg, png, gif',
            'layoutGridColumnSpan' => 4,
            'layoutGroupId' => '3b7dae73',
            'uploadMediaLibrary' => true,
            'gpfupEnable' => true,
        ),
        array(
            'type' => 'fileupload',
            'id' => 13,
            'label' => 'Additional Image',
            'description' => 'Upload an optional image to complement the article. These are displayed at the bottom of the article page.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'maxFiles' => 1,
            'multipleFiles' => true,
            'allowedExtensions' => 'jpg, jpeg, png, gif',
            'layoutGridColumnSpan' => 4,
            'layoutGroupId' => '3b7dae73',
            'uploadMediaLibrary' => true,
            'gpfupEnable' => true,
        ),
        array(
            'type' => 'fileupload',
            'id' => 14,
            'label' => 'Additional Image',
            'description' => 'Upload an optional image to complement the article. These are displayed at the bottom of the article page.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'maxFiles' => 1,
            'multipleFiles' => true,
            'allowedExtensions' => 'jpg, jpeg, png, gif',
            'layoutGridColumnSpan' => 4,
            'layoutGroupId' => '3b7dae73',
            'uploadMediaLibrary' => true,
            'gpfupEnable' => true,
        ),
        array(
            'type' => 'fileupload',
            'id' => 15,
            'label' => 'Additional Image',
            'description' => 'Upload an optional image to complement the article. These are displayed at the bottom of the article page.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'maxFiles' => 1,
            'multipleFiles' => true,
            'allowedExtensions' => 'jpg, jpeg, png, gif',
            'layoutGridColumnSpan' => 4,
            'layoutGroupId' => '3b7dae73',
            'uploadMediaLibrary' => true,
            'gpfupEnable' => true,
        ),
        array(
            'type' => 'date',
            'id' => 16,
            'label' => 'Date',
            'description' => 'Please specify the date for this release to be published. If left unmarked the article will be published immediately.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'dateType' => 'datepicker',
            'dateFormat' => 'mdy',
            'layoutGridColumnSpan' => 4,
            'layoutGroupId' => '385bdcc8',
        ),
        array(
            'type' => 'time',
            'id' => 17,
            'label' => 'Time',
            'description' => 'Please specify the time for this release to be published. If left unmarked the article will be published immediately.',
            'isRequired' => false,
            'size' => 'large',
            'visibility' => 'visible',
            'timeFormat' => '12',
            'layoutGridColumnSpan' => 5,
            'layoutSpacerGridColumnSpan' => 3,
            'layoutGroupId' => '385bdcc8',
        ),
    ),
    'button' => array(
        'type' => 'text',
        'text' => 'Submit',
        'width' => 'auto',
        'location' => 'bottom',
        'layoutGridColumnSpan' => 9,
    ),
    'confirmations' => array(
        array(
            'id' => '64ac7f15b14d1',
            'name' => 'Default Confirmation',
            'isDefault' => true,
            'type' => 'message',
            'message' => '<h2>Your post submission was successfully submitted.</h2>If you scheduled the post, it will be published live on the date/time you specified. If you did not enter a publish date, you will need to submit a request to the IT/WebDev team in order to publish the post live.<br><br>Link: <a href="https://airtable.com/appjSeRIK0tnX5ymN/shrmXeElnE5zZgYz6">WebDev Request Form</a>',
        ),
    ),
    'notifications' => array(
        array(
            'id' => '64ac7f15b133e',
            'isActive' => true,
            'to' => 'fischer@psi.edu',
            'name' => 'Alan\'s Notification',
            'event' => 'form_submission',
            'toType' => 'email',
            'subject' => 'New {Category:5} from PSI',
            'message' => 'Below is the URL for the {Category:5}<br><br>{post_permalink}',
        ),
    ),
);
